development:
  # adapter: sqlite3
  # database: db/development.sqlite3
  host: ''
  adapter: postgresql
  database: bmasb_development
  username: fernando
  # password:

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   host: localhost
#   min_messages: warning
#   username:

production:
  # adapter: sqlite3
  # database: db/development.sqlite3
  host: ''
  adapter: postgresql
  database: bmasb_production
  username: fernando
  # password:
