# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).on 'turbolinks:load', ->
  $('#event_shop_id').select2
    theme: 'bootstrap'
    placeholder: 'Elige una tienda'
    allowClear: true
  return

  $('.eventDatePicker').datepicker
    language: 'es'
    autoclose: true
    todayHighlight: true

# ---
# generated by js2coffee 2.2.0
